services:
  # Backend: Django (Logística)
  - type: web
    name: ops-reports-api
    plan: free
    runtime: python
    env: python
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        # Aqui o Render vai esperar você preencher a URL do Supabase no Dashboard
        sync: false 
      - key: ALLOWED_HOSTS
        value: "*"
