# Generated by Django 6.0.3 on 2026-04-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado'), ('PLANEJAMENTO', 'Planejamento')], default='EM_ANDAMENTO', max_length=20),
        ),
    ]
