# Generated by Django 6.0.3 on 2026-04-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='squad',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
