# Generated by Django 6.0.3 on 2026-04-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_project_squad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PLANEJAMENTO', 'Planejado'), ('EM_IMPLANTACAO', 'Em Implantação'), ('ENTREGUE', 'Entregue')], default='EM_ANDAMENTO', max_length=20),
        ),
    ]
