# Generated by Django 6.0.3 on 2026-04-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='total_score',
        ),
        migrations.AddField(
            model_name='project',
            name='delivery_count',
            field=models.IntegerField(default=0, help_text='Quantidade de entregas do cliente (coluna Total da planilha)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PLANEJAMENTO', 'Planejado'), ('EM_IMPLANTACAO', 'Em Implantação'), ('ENTREGUE', 'Entregue')], default='PLANEJAMENTO', max_length=20),
        ),
    ]
